# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todoListiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya/RxSwift'
  pod 'Eureka'
  pod 'DeviceKit', '~> 1.3'
  pod 'MBProgressHUD', '~> 1.1.0'
  # Pods for todoListiOS

  target 'todoListiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todoListiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
